### ISSUE TITLE
Why not semver?

### ISSUE THREAD

**Issue by Guts** [jiri-otoupal/pycrosskit#11]
Hi @jiri-otoupal,

Thanks for your small but useful package.

Is there any particular reason not to follow Semver, the recommended convention for Python packages?

Ref: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#semantic-versioning-preferred

**Comment by jiri-otoupal** [comment]
Fixed, thanks for bringing this up

**Comment by Guts** [comment]
> Fixed, thanks for bringing this up, and your changes ! It is amazing when somebody helps out.

Thanks you to react so quickly :).

What's your release schedule?
