### ISSUE TITLE
Python 3.11.x support?

### ISSUE THREAD

**Issue by darkmastermindz** [jiri-otoupal/pycrosskit#34]
Hi @jiri-otoupal, quick question - does this package currently support the latest Python 3.11?

**Comment by jiri-otoupal** [comment]
Hi will check it, but there shouldn't be any problem

**Comment by darkmastermindz** [comment]
I tried it and it seems to be working, but definitely would like to see validation and mention of support on PyPi and Readme

**Comment by jiri-otoupal** [comment]
Added Python 3.11 support. Thank you for addressing that have a nice day !
